# Generated by Django 5.2.6 on 2025-09-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Is banned'),
        ),
    ]
