# Generated by Django 5.2.6 on 2025-09-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='deleted_at',
            field=models.DateField(blank=True, null=True, verbose_name='Deleted date'),
        ),
    ]
