# Generated by Django 5.2.6 on 2025-10-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name'], 'permissions': [('can_publish_author', 'Can publish author')], 'verbose_name': 'Publisher', 'verbose_name_plural': 'Publishers'},
        ),
    ]
